### ISSUE TITLE
Ad Slot not working on mobile

### ISSUE THREAD

**Issue by divyenduz** [seeden/react-google-publisher-tag#1]
Hi, 

I am using this component with `react-responsive` component to display google ads on desktop and mobile.

My component is not working on mobile, I can't find the ad slot when I append ?googfc to my url.

My usage of this component is like

```
import GoogleAd from 'react-google-publisher-tag';

<GoogleAd
    path="/-----/-----"
    format={"RECTANGLE"} />

<GoogleAd
    path="/-----/-----"
    format={"VERTICAL"} />

<GoogleAd
    path="/-----/-----"
    mobile={true}
    format={"HORIZONTAL"} />
```

The first two are working while the 3rd one is not. First one is a 300x250, 2nd one is a 300x600 and 3rd one is 320x50. I also tried using the 3rd component as 

```
<GoogleAd
    path="/-----/-----"
    mobile={true}
    format={"MOBILE"} />
```

Using mobile for format, which is not documented yet but I saw that it has been done in the code.

And pointers on what could be going wrong ?

**Comment by seeden** [comment]
I am sorry but documentation is out of date. I will update it today. There is no mobile parameter. It was mess in the old version. You can use these sizes (or you can use your own):

``` js
export const Dimensions = {
  [Format.HORIZONTAL]: [[970, 90], [728, 90], [468, 60], [234, 60]],
  [Format.RECTANGLE]: [[336, 280], [300, 250], [250, 250], [200, 200], [180, 150], [125, 125]],
  [Format.VERTICAL]: [[300, 600], [160, 600], [120, 600], [120, 240]],
  [Format.MOBILE]: [[320, 50]],
  '300x600': [[300, 600], [160, 600]],
  '336x280': [[336, 280], [300, 250]],
  '728x90': [[728, 90], [468, 60]],
  '970x90': [[970, 90], [728, 90], [468, 60]],
};
```

As you can see the horizontal dimension have no MOBILE size (320x50). 
First of all do not forget to write correct dimensions into the your google publisher tag account.
There is one more condition: holder of the AD needs to have a min width equal 320px. If you wont to turn off this feature you need to set property responsive={false};
Let me know if is it working for you? 

Sometimes you are not able to see any ad because the adsense are not going to send you any.

**Comment by divyenduz** [comment]
Adding the width to ad container worked for me, closing this one, thanks.
